### ISSUE TITLE
Make program exit clean

### ISSUE THREAD

**Issue by ubx** [ubx/Video-and-Can-Replayer#2]

**Comment by ubx** [comment]
Partly fixed in 9df79fc (only if no map displayed)

**Comment by ubx** [comment]
Fix for map displayed a17a797.

**Comment by ubx** [comment]
Still to fix:

 Exception in thread CanSender:
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/home/andreas/IdeaProjects/Video-and-Can-Replayer/cansender.py", line 48, in run
     if self.reader:
   File "/home/andreas/IdeaProjects/Video-and-Can-Replayer/sqlite2.py", line 35, in __len__
     result = self._cursor.execute("SELECT COUNT(*) FROM {} where ts >= {:f}".format(self.table_name, self.start_time))
 sqlite3.ProgrammingError: bad parameter or other API misuse

**Comment by ubx** [comment]
Fixed in 9fd6d40.
