### ISSUE TITLE
AttributeError when running with a Windows exe

### ISSUE THREAD

**Issue by ubx** [ubx/Video-and-Can-Replayer#4]
dist\VideoAndCanPlayer2.exe config2.json --map
fcntl not available on this platform
libc is unavailable
WARNING Can channel vcan0 not connected
[INFO   ] [Logger      ] Record log in C:\Users\Andreas\.kivy\logs\kivy_20-02-03_101.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\Andreas\AppData\Local\Temp\_MEI66562\kivy\__init__.pyc"
[INFO   ] [Python      ] v3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Andreas\IntelliJ-ws\Video-and-Can-Replayer\dist\VideoAndCanPlayer2.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'3.1.0 - Build 9.17.10.4459'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 3000'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'1.40 - Intel Build 9.17.10.4459'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Video       ] Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "kivy\properties.pyx", line 860, in kivy.properties.ObservableDict.__getattr__
 KeyError: 'mapview'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "VideoAndCanPlayer2.py", line 73, in <module>
     main()
   File "VideoAndCanPlayer2.py", line 60, in main
     VideoplayerApp(videofilename, syncpoints, bookmarks, cansender, position_srv).run()
   File "site-packages\kivy\app.py", line 855, in run
   File "site-packages\kivy\base.py", line 504, in runTouchApp
   File "site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
   File "site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
   File "site-packages\kivy\base.py", line 339, in idle
   File "site-packages\kivy\clock.py", line 591, in tick
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "videoplayer.py", line 105, in clock_callback
     self.mainwindow.ids.mapview.center_on(self.lat, self.lon)
   File "kivy\properties.pyx", line 863, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'
[12872] Failed to execute script VideoAndCanPlayer2

**Comment by ubx** [comment]
Running it as an executable on Windows is not an option!
